import { type InsertAIModelRow } from '../schema';

export const models: InsertAIModelRow[] = [
  {
    id: 'gpt-4.1',
    name: 'GPT-4.1',
    description: 'GPT-4.1 model',
    provider: 'openai',
    type: 'text',
    isEnabled: false,
  },
  {
    id: 'gpt-4.1-mini',
    name: 'GPT-4.1 Mini',
    description: 'GPT-4.1 Mini model',
    provider: 'openai',
    type: 'text',
    isEnabled: false,
  },
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    description: 'GPT-4o model',
    provider: 'openai',
    type: 'text',
    isEnabled: false,
  },
  {
    id: 'gemini-2.5-pro-preview-06-05',
    name: 'Gemini 2.5 Pro',
    description: 'Gemini 2.5 Pro model',
    provider: 'google',
    type: 'text',
    isEnabled: true,
  },
  {
    id: 'gemini-2.5-flash-preview-05-20',
    name: 'Gemini 2.5 Flash',
    description: 'Gemini 2.5 Flash model',
    provider: 'google',
    type: 'text',
    isEnabled: true,
  },
  {
    id: 'gemini-2.0-flash',
    name: 'Gemini 2.0 Flash',
    description: 'Gemini 2.0 Flash model',
    provider: 'google',
    type: 'text',
    isEnabled: false,
  },
  {
    id: 'claude-3-7-sonnet-20250219',
    name: 'Claude 3.7 Sonnet',
    description: 'Claude 3.7 Sonnet model',
    provider: 'anthropic',
    type: 'text',
    isEnabled: true,
  },
  {
    id: 'claude-sonnet-4-20250514',
    name: 'Claude 4 Sonnet',
    description: 'Most advanced model from Anthropic',
    provider: 'anthropic',
    type: 'text',
    isEnabled: true,
    isDefault: true,
  },
  {
    id: 'pixtral-large-latest',
    name: 'Pixtral Large',
    description:
      'Pixtral Large Latest Model (Mistral) - A large language model designed for various tasks.',
    provider: 'mistral',
    type: 'text',
    isEnabled: true,
  },
  {
    id: 'grok-2-vision-1212',
    name: 'Grok 2',
    description: 'xAI Grok-2 - A large language model designed for various tasks.',
    provider: 'xai',
    type: 'text',
    isEnabled: true,
  },
];
