services:
  postgres:
    image: ankane/pgvector
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: local-nextjs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: h4yuasd6
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d local-nextjs']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mailhog
    restart: always
    ports:
      - '8025:8025'
      - '1025:1025'

volumes:
  postgres_data:
    driver: local
