name: E2E Tests

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]

  workflow_dispatch:

jobs:
  e2e:
    if: ${{ github.event.pull_request.draft == false }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Load 1password secrets
        uses: 1password/load-secrets-action@v1
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          NEXTAUTH_SECRET: 'op://chat-app/.env.staging/NEXTAUTH_SECRET'
          NEXTAUTH_URL: 'op://chat-app/.env.staging/NEXTAUTH_URL'
          DATABASE_URL: 'op://chat-app/.env.staging/DATABASE_URL'
          MAILJET_API_KEY: 'op://chat-app/API Keys/MAILJET_API_KEY'
          MAILJET_API_SECRET: 'op://chat-app/API Keys/MAILJET_API_SECRET'
          DEV_MODE: 'op://chat-app/.env.staging/DEV_MODE'
          GITHUB_CLIENT_ID: 'op://chat-app/.env.staging/GITHUB_CLIENT_ID'
          GITHUB_CLIENT_SECRET: 'op://chat-app/.env.staging/GITHUB_CLIENT_SECRET'
          AWS_ACCESS_KEY_ID: 'op://chat-app/API Keys/AWS_ACCESS_KEY_ID'
          AWS_SECRET_ACCESS_KEY: 'op://chat-app/API Keys/AWS_SECRET_ACCESS_KEY'
          AWS_S3_ENDPOINT_URL: 'op://chat-app/API Keys/AWS_S3_ENDPOINT_URL'
          UTILS_API_URL: 'op://chat-app/API Keys/UTILS_API_URL'
          UTILS_API_KEY: 'op://chat-app/API Keys/UTILS_API_KEY'
          GOOGLE_CLIENT_ID: 'op://chat-app/API Keys/GOOGLE_CLIENT_ID'
          GOOGLE_CLIENT_SECRET: 'op://chat-app/API Keys/GOOGLE_CLIENT_SECRET'
          JWT_SECRET: 'op://chat-app/.env.staging/JWT_SECRET'
          OPENAI_API_KEY: 'op://chat-app/API Keys/OPENAI_API_KEY'
          ELEVENLABS_API_KEY: 'op://chat-app/API Keys/ELEVENLABS_API_KEY'
          BRAVE_API_KEY: 'op://chat-app/API Keys/BRAVE_API_KEY'
          ANTHROPIC_API_KEY: 'op://chat-app/API Keys/ANTHROPIC_API_KEY'
          GEMINI_API_KEY: 'op://chat-app/API Keys/GEMINI_API_KEY'
          MISTRAL_API_KEY: 'op://chat-app/API Keys/MISTRAL_API_KEY'
          XAI_API_KEY: 'op://chat-app/API Keys/XAI_API_KEY'
          NOTION_CLIENT_ID: 'op://chat-app/API Keys/NOTION_CLIENT_ID'
          NOTION_CLIENT_SECRET: 'op://chat-app/API Keys/NOTION_CLIENT_SECRET'
          NOTION_REDIRECT_URI: 'op://chat-app/.env.staging/NOTION_REDIRECT_URI'
          STRIPE_WEBHOOK_SECRET: 'op://chat-app/.env.staging/STRIPE_WEBHOOK_SECRET'
          STRIPE_SECRET_KEY: 'op://chat-app/.env.staging/STRIPE_SECRET_KEY'
          NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: 'op://chat-app/.env.staging/NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY'
          GITHUB_ACCESS_TOKEN: 'op://chat-app/API Keys/GITHUB_ACCESS_TOKEN'
          E2E_USER_EMAIL: 'op://chat-app/.env.e2e/E2E_USER_EMAIL'
          E2E_USER_PASSWORD: 'op://chat-app/.env.e2e/E2E_USER_PASSWORD'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm install -g pnpm@9.15.3 && pnpm install

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps chromium

      - name: Run Playwright tests
        run: pnpm exec playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
